name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy over SSH
      run: |
          cd /home/stella/gfl-tag
          git pull origin main
          docker compose up --build -d
